#!/usr/bin/env python3
"""Prometheus exporter for the RabbitMQ Management HTTP API.

Polls /api/overview, /api/queues and /api/nodes on every scrape and exposes
the values as Prometheus metrics.

Usage:
    MIAGENT_TARGET_USERNAME=U MIAGENT_TARGET_PASSWORD=P \
        python exporter.py --port PORT --target BASE_URL

Test fixture: model-generated by `miagent generate` against
examples/rabbitmq/mock_server.py, then hand-edited only to the env-var
credential contract. Exercised in CI with no LLM calls.
"""

import argparse
import logging
import os
import sys
import time
from typing import Any, Dict, Iterable, List, Optional, Tuple

import httpx
from prometheus_client import start_http_server
from prometheus_client.core import (
    REGISTRY,
    CounterMetricFamily,
    GaugeMetricFamily,
)

LOG = logging.getLogger("rabbitmq_exporter")

HTTP_TIMEOUT_SECONDS = 5.0

# (metric name, help, JSON path inside /api/overview)
OVERVIEW_COUNTERS: List[Tuple[str, str, Tuple[str, ...]]] = [
    (
        "rabbitmq_messages_published_total",
        "Total number of messages published across the broker (cumulative).",
        ("message_stats", "publish"),
    ),
    (
        "rabbitmq_messages_delivered_get_total",
        "Total number of messages delivered to consumers in ack mode plus basic.get (cumulative).",
        ("message_stats", "deliver_get"),
    ),
    (
        "rabbitmq_messages_acked_total",
        "Total number of messages acknowledged (cumulative).",
        ("message_stats", "ack"),
    ),
    (
        "rabbitmq_messages_confirmed_total",
        "Total number of messages confirmed (cumulative).",
        ("message_stats", "confirm"),
    ),
]

OVERVIEW_GAUGES: List[Tuple[str, str, Tuple[str, ...]]] = [
    (
        "rabbitmq_messages",
        "Total number of messages in all queues.",
        ("queue_totals", "messages"),
    ),
    (
        "rabbitmq_messages_ready",
        "Number of messages ready for delivery across all queues.",
        ("queue_totals", "messages_ready"),
    ),
    (
        "rabbitmq_messages_unacknowledged",
        "Number of messages delivered but not yet acknowledged across all queues.",
        ("queue_totals", "messages_unacknowledged"),
    ),
    (
        "rabbitmq_connections",
        "Current number of connections.",
        ("object_totals", "connections"),
    ),
    (
        "rabbitmq_channels",
        "Current number of channels.",
        ("object_totals", "channels"),
    ),
    (
        "rabbitmq_exchanges",
        "Current number of exchanges.",
        ("object_totals", "exchanges"),
    ),
    (
        "rabbitmq_queues",
        "Current number of queues.",
        ("object_totals", "queues"),
    ),
    (
        "rabbitmq_consumers",
        "Current number of consumers.",
        ("object_totals", "consumers"),
    ),
]

# (metric name, help, JSON path inside each /api/queues element)
QUEUE_GAUGES: List[Tuple[str, str, Tuple[str, ...]]] = [
    (
        "rabbitmq_queue_messages",
        "Total number of messages in the queue.",
        ("messages",),
    ),
    (
        "rabbitmq_queue_messages_ready",
        "Number of messages in the queue ready for delivery.",
        ("messages_ready",),
    ),
    (
        "rabbitmq_queue_messages_unacknowledged",
        "Number of messages in the queue delivered but awaiting acknowledgement.",
        ("messages_unacknowledged",),
    ),
    (
        "rabbitmq_queue_consumers",
        "Number of consumers on the queue.",
        ("consumers",),
    ),
    (
        "rabbitmq_queue_memory_bytes",
        "Bytes of memory used by the queue process.",
        ("memory",),
    ),
]

QUEUE_COUNTERS: List[Tuple[str, str, Tuple[str, ...]]] = [
    (
        "rabbitmq_queue_messages_published_total",
        "Total number of messages published to the queue (cumulative).",
        ("message_stats", "publish"),
    ),
]

# (metric name, help, JSON path inside each /api/nodes element)
NODE_GAUGES: List[Tuple[str, str, Tuple[str, ...]]] = [
    (
        "rabbitmq_node_memory_used_bytes",
        "Memory used by the node, in bytes.",
        ("mem_used",),
    ),
    (
        "rabbitmq_node_file_descriptors_used",
        "Number of file descriptors in use by the node.",
        ("fd_used",),
    ),
    (
        "rabbitmq_node_file_descriptors_total",
        "Number of file descriptors available to the node.",
        ("fd_total",),
    ),
    (
        "rabbitmq_node_sockets_used",
        "Number of sockets in use by the node.",
        ("sockets_used",),
    ),
    (
        "rabbitmq_node_sockets_available",
        "Number of sockets available to the node.",
        ("sockets_total",),
    ),
    (
        "rabbitmq_node_processes_used",
        "Number of Erlang processes in use on the node.",
        ("proc_used",),
    ),
    (
        "rabbitmq_node_processes_available",
        "Number of Erlang processes available on the node.",
        ("proc_total",),
    ),
    (
        "rabbitmq_node_uptime_milliseconds",
        "Milliseconds since the node started.",
        ("uptime",),
    ),
    (
        "rabbitmq_node_disk_free_bytes",
        "Free disk space on the node, in bytes.",
        ("disk_free",),
    ),
]

NODE_RUNNING_NAME = "rabbitmq_node_running"
NODE_RUNNING_HELP = "Whether the node is running (1 = running, 0 = not running)."


def _dig(obj: Any, path: Tuple[str, ...]) -> Any:
    """Walk a nested dict by key path; return None if any step is missing."""
    cur = obj
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return None
        cur = cur[key]
    return cur


def _to_number(value: Any) -> Optional[float]:
    """Convert a JSON numeric value to float; reject bools, strings, None."""
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return None


def _to_bool_number(value: Any) -> Optional[float]:
    """Map a JSON boolean (or 0/1 number) to 1.0 / 0.0."""
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, (int, float)):
        return 1.0 if value else 0.0
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in ("true", "running", "1"):
            return 1.0
        if lowered in ("false", "stopped", "0"):
            return 0.0
    return None


class RabbitMQCollector:
    """Custom collector that queries the RabbitMQ management API per scrape."""

    def __init__(
        self,
        target: str,
        username: Optional[str],
        password: Optional[str],
    ) -> None:
        self._target = target.rstrip("/")
        auth = None
        if username is not None or password is not None:
            auth = httpx.BasicAuth(username or "", password or "")
        self._client = httpx.Client(
            base_url=self._target,
            auth=auth,
            timeout=httpx.Timeout(HTTP_TIMEOUT_SECONDS),
            headers={"Accept": "application/json"},
        )

    def _fetch(self, path: str) -> Any:
        """GET a JSON endpoint; return parsed JSON or None on any failure."""
        try:
            resp = self._client.get(path)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as exc:
            LOG.error(
                "HTTP %s from %s%s: %s",
                exc.response.status_code,
                self._target,
                path,
                exc,
            )
        except httpx.HTTPError as exc:
            LOG.error("Request to %s%s failed: %s", self._target, path, exc)
        except ValueError as exc:
            LOG.error("Invalid JSON from %s%s: %s", self._target, path, exc)
        except Exception as exc:  # noqa: BLE001 - never crash a scrape
            LOG.error("Unexpected error fetching %s%s: %s", self._target, path, exc)
        return None

    def _collect_overview(self) -> Iterable[Any]:
        data = self._fetch("/api/overview")
        if data is None:
            return
        if not isinstance(data, dict):
            LOG.error("Unexpected /api/overview payload type: %s", type(data).__name__)
            return

        for name, help_text, path in OVERVIEW_COUNTERS:
            value = _to_number(_dig(data, path))
            if value is None:
                continue
            fam = CounterMetricFamily(name, help_text)
            fam.add_metric([], value)
            yield fam

        for name, help_text, path in OVERVIEW_GAUGES:
            value = _to_number(_dig(data, path))
            if value is None:
                continue
            fam = GaugeMetricFamily(name, help_text)
            fam.add_metric([], value)
            yield fam

    def _collect_queues(self) -> Iterable[Any]:
        data = self._fetch("/api/queues")
        if data is None:
            return
        if not isinstance(data, list):
            LOG.error("Unexpected /api/queues payload type: %s", type(data).__name__)
            return

        labels = ["queue", "vhost"]
        gauges: Dict[str, GaugeMetricFamily] = {
            name: GaugeMetricFamily(name, help_text, labels=labels)
            for name, help_text, _ in QUEUE_GAUGES
        }
        counters: Dict[str, CounterMetricFamily] = {
            name: CounterMetricFamily(name, help_text, labels=labels)
            for name, help_text, _ in QUEUE_COUNTERS
        }
        seen = set()

        for item in data:
            if not isinstance(item, dict):
                continue
            qname = item.get("name")
            vhost = item.get("vhost")
            if qname is None or vhost is None:
                continue
            label_values = [str(qname), str(vhost)]
            key = tuple(label_values)
            if key in seen:
                continue
            seen.add(key)

            for name, _, path in QUEUE_GAUGES:
                value = _to_number(_dig(item, path))
                if value is not None:
                    gauges[name].add_metric(label_values, value)

            for name, _, path in QUEUE_COUNTERS:
                value = _to_number(_dig(item, path))
                if value is not None:
                    counters[name].add_metric(label_values, value)

        for fam in gauges.values():
            yield fam
        for fam in counters.values():
            yield fam

    def _collect_nodes(self) -> Iterable[Any]:
        data = self._fetch("/api/nodes")
        if data is None:
            return
        if not isinstance(data, list):
            LOG.error("Unexpected /api/nodes payload type: %s", type(data).__name__)
            return

        labels = ["node"]
        gauges: Dict[str, GaugeMetricFamily] = {
            name: GaugeMetricFamily(name, help_text, labels=labels)
            for name, help_text, _ in NODE_GAUGES
        }
        running = GaugeMetricFamily(NODE_RUNNING_NAME, NODE_RUNNING_HELP, labels=labels)
        seen = set()

        for item in data:
            if not isinstance(item, dict):
                continue
            node = item.get("name")
            if node is None:
                continue
            node = str(node)
            if node in seen:
                continue
            seen.add(node)
            label_values = [node]

            for name, _, path in NODE_GAUGES:
                value = _to_number(_dig(item, path))
                if value is not None:
                    gauges[name].add_metric(label_values, value)

            run_value = _to_bool_number(item.get("running"))
            if run_value is not None:
                running.add_metric(label_values, run_value)

        for fam in gauges.values():
            yield fam
        yield running

    def collect(self) -> Iterable[Any]:
        for section in (self._collect_overview, self._collect_queues, self._collect_nodes):
            try:
                yield from section()
            except Exception as exc:  # noqa: BLE001 - never crash a scrape
                LOG.error("Error collecting %s: %s", section.__name__, exc)

    def describe(self) -> Iterable[Any]:
        # Returning nothing prevents a live API call during registration.
        return []


def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prometheus exporter for RabbitMQ.")
    parser.add_argument("--port", type=int, required=True, help="Port to serve /metrics on.")
    parser.add_argument(
        "--target",
        required=True,
        help="Base URL of the RabbitMQ management API, e.g. http://127.0.0.1:15672",
    )
    return parser.parse_args(argv)


def main() -> None:
    logging.basicConfig(
        stream=sys.stderr,
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    args = parse_args()

    collector = RabbitMQCollector(
        args.target,
        os.environ.get("MIAGENT_TARGET_USERNAME"),
        os.environ.get("MIAGENT_TARGET_PASSWORD"),
    )
    REGISTRY.register(collector)

    start_http_server(args.port)
    LOG.info("Serving metrics on :%d/metrics for target %s", args.port, args.target)

    try:
        while True:
            time.sleep(3600)
    except KeyboardInterrupt:
        LOG.info("Shutting down")


if __name__ == "__main__":
    main()
